# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1si_uWslIXUv10rbxgaSs3OtldIkfgyVJ
"""

!pip install -q kaggle

from google.colab import files
files.upload()

! mkdir ~/.kaggle

! cp kaggle.json ~/.kaggle/

! chmod 600 ~/.kaggle/kaggle.json

! kaggle datasets list

! pip install opendatasets

import opendatasets as od
od.download("https://www.kaggle.com/datasets/mahmoudelhemaly/students-grading-dataset/code")

import pandas as pd
data=pd.read_csv("/content/students-grading-dataset/Students_Grading_Dataset.csv")
data.head()